version: '3.8'

name: embeddingserver

services:
  db:
    ipc: host
    container_name: embedding-db
    build:
      context: ./python/
      dockerfile: Dockerfile
    env_file: ./python/.env
    image: purplelemons/embedding-db
    volumes:
      - /etc/embeddingserver/data:/app/db/data
    tty: true
    restart: always
    

  web:
    links:
     - "db"
    container_name: embedding-web
    build: .
    image: purplelemons/embedding-web
    ports:
     - 3658:8181
    restart: always
    env_file: .env 
