version: '3.8'

services:
  db:
    ipc: host
    container_name: embedding-db
    build:
      context: ./python/
      dockerfile: Dockerfile
    image: purplelemons/embedding-db
    volumes:
      - data:/app/db/data
    tty: true
    restart: always

  web:
    links:
     - "db"
    container_name: embedding-web
    build: .
    image: purplelemons/embedding-web
    ports: 
     - 3658:8181
    #depends_on: 
    # - db
    restart: always

volumes:
  data: {}
