openapi: 3.1.0
info:
  title: Web Search
  description:
    Use Web Search to search the web and get page summaries. Try changing your query prompt if you aren't
    getting the desired results.
  version: 1.1.3
servers:
  - url: https://gptsearch.cyberthing.dev
    description: Search server
paths:
  /self:
    get:
      operationId: self
      summary: Query the API about a topic you have already researched. This is by far the fastest search method so try it first
      parameters:
        - name: q
          in: query
          required: true
          description: The search string
          schema:
            type: string
      responses:
        "200":
          description: The current version of the API
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: string
                  date:
                    type: string
                    description: The current GMT date and time
  /search:
    get:
      operationId: query
      summary: Perform a custom Web search and return snippets and their urls
      parameters:
        - name: q
          in: query
          required: true
          description: The search string
          schema:
            type: string
      responses:
        "200":
          description: An array of search results and the current time
          content:
            application/json:
              schema:
                type: object
                properties:
                  links:
                    type: array
                    description: Relevant links
                    items:
                      type: string
                  date:
                    type: string
                    description: The current GMT date and time
                  results:
                    type: array
                    items:
                      type: string
  /browse:
    post:
      x-openai-isConsequential: false
      operationId: browse
      summary: Get relevant paragraphs to your site query. Both url and topic are required.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                topic:
                  type: string
                  description: What information you want to get from the site
      responses:
        "200":
          description: The best matches in the database.
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: string
