name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  run: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout latest
      uses: actions/checkout@v4.1.1
    - name: Use inside docker
      uses: docker://bookworm-slim:latest
    - name: Create ENV
      run: |
        ls
        ls python
        touch .env
        touch python/.env
        echo "${{ secrets.ENV }}" > .env
        cat .env > python/.env
        cat .env
    - name: Compose UP
      run: docker compose -f docker-compose.yml up --build
